spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID} # Our User Google ID
            client-secret: ${GOOGLE_CLIENT_SECRET} # Secret Google give us to register the client (our app) to google ?
            redirect-uri: "http://localhost:8055/api/v1/auth-test/greeting"

            client-name: google
            scope: # Data we (our app) want from the 3rd Party (Gmail)
              - openid # For OpenID Connect
              - profile
              - email
          facebook:
            client-id: ${FACEBOOK_CLIENT_ID}
            client-secret: ${FACEBOOK_CLIENT_SECRET}
            redirect-uri: "http://localhost:8055/api/v1/auth-test/greeting"
            scope:
              - email
              - public_profile
              - openid
            client-name: Facebook

        provider:
          google:
            authorization-uri: https://accounts.google.com/o/oauth2/v2/auth  # Authorization Server
            token-uri: https://oauth2.googleapis.com/token # How our app will exchange tokens with the resources server
            user-info-uri: https://www.googleapis.com/oauth2/v3/userinfo # Get the user data after access token
          facebook:
            authorization-uri: https://www.facebook.com/v9.0/dialog/oauth
            token-uri: https://graph.facebook.com/v9.0/oauth/access_token
            user-info-uri: https://graph.facebook.com/me?fields=id,name,email
            user-name-attribute: id



  mail:
    host: smtp.gmail.com
    port: 587
    default-encoding: UTF-8
    username: ${gmail_username}
    password: ${gmail_password}
    properties:
      mail:
        smtp:
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000
          auth: true
          starttls:
            enable: true
            required: true
  #          ssl: # port = 465
  #            trust: smtp.gmail.com
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/mehna
    username: root
    password: MyNewPass!@$$#@
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: 'create-drop'
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  data:
    redis:
      database: 0
      host: localhost
      port: 8099
      repositories:
        enabled: false

  cache:
    type: REDIS

  application:
    name: auth-system

server:
  port: 8055

logging:
  level:
    org:
      hibernate:
        type: trace
        stat: debug
      springframework:
        security: debug

application:
  security:
    jwt:
      expiration:
        access-token: 900000 # 15 mins
        refresh-token: 432000000 # 5 days








